spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB.PASSWORD}
    url: jdbc:postgresql://localhost:${DB.PORT}/${DB.SCHEMA}
    username: ${DB.USERNAME}

flyway:
  createSchemas: false
  initSql: CREATE IF NOT EXISTS a3crm
  schemas: ${DB.SCHEMA}


